export enum ProfessionEnum {
  SELF_EMPLOYED = 'SELF_EMPLOYED',
  BUSINESS = 'BUSINESS',
  EMPLOYEE = 'EMPLOYEE',
}

export enum ProductEnum {
  IAP = 'IAP',
  SIP = 'SIP',
}

export enum LeadStatus {
  PENDING = 'PENDING',
  ASSIGNED = 'ASSIGNED',
  ON_HOLD = 'ON_HOLD',
  CLOSED = 'CLOSED',
  OPEN = 'OPEN',
}

export enum ClientStage {
  FIRST_TALK_DONE = 'FIRST_TALK_DONE',
  FOLLOWING_UP = 'FOLLOWING_UP',
  CLIENT_INTERESTED = 'CLIENT_INTERESTED',
  ACCOUNT_OPENED = 'ACCOUNT_OPENED',
  NO_RESPONSE_DORMANT = 'NO_RESPONSE_DORMANT',
  NOT_INTERESTED_DORMANT = 'NOT_INTERESTED_DORMANT',
  RISKY_CLIENT_DORMANT = 'RISKY_CLIENT_DORMANT',
  HIBERNATED = 'HIBERNATED',
}

export enum PhoneLabel {
  PRIMARY = 'PRIMARY',
  MOBILE = 'MOBILE',
  WHATSAPP = 'WHATSAPP',
  WORK = 'WORK',
  HOME = 'HOME',
  OTHER = 'OTHER',
}

export enum LeadEventType {
  REVISIT = 'REVISIT',
  NOTE = 'NOTE',
  INTERACTION = 'INTERACTION',
  STATUS_CHANGE = 'STATUS_CHANGE',
  ASSIGNMENT = 'ASSIGNMENT',
  PHONE_ADDED = 'PHONE_ADDED',
  PHONE_REMOVED = 'PHONE_REMOVED',
  PHONE_MARKED_PRIMARY = 'PHONE_MARKED_PRIMARY',
  REMARK_UPDATED = 'REMARK_UPDATED',
  BIO_UPDATED = 'BIO_UPDATED',
  HISTORY_SNAPSHOT = 'HISTORY_SNAPSHOT',
}
